### ISSUE TITLE
Getting stuck after teleportation

### ISSUE THREAD

**Issue by TeaWald** [stormytuna/KindTeleporters#2]
In orbit, the mod works as expected. it seems (it is not)
I tested it on the first moon 
When teleporting, things that are not in your hands are dumped on the floor as expected (and u not stuk)

If held an item on teleportation:
1. You're standing in a teleport and you can't move but can interact (move teleporter away not helping)
2. (twohanded item only) If you throw an object on the floor, then nails the character to one of the walls of the ship, also do collision damage. not happens with small objects, just keeps stuck in place
3. It seems that if there were no walls, the character would rush to infinity with constant acceleration 
4. Happened to me when the collision failed and I flew into out of bounds to infinity and beyond

Nevertheless, a regular teleporter still can be used. You need to teleport again, removing everything from your hands 
(NOT throwing two-handed objects on the floor, it can be fatal) this will set you free

**Comment by stormytuna** [comment]
Closing as completed at some point - sorry for not getting back to you sooner
