### ISSUE TITLE
Negative Weight

### ISSUE THREAD

**Issue by SaladProphet** [stormytuna/KindTeleporters#3]
When teleporting while holding an object, when you arrive on the ship your weight will be set to zero regardless of what you are holding, and dropping the item causes you to have negative weight (only displays as zero) and will only go into positive weight if you are heavier than when you warped, this has the side affect of making you MUCH faster, depending on how heavy the object was.
In the meantime players can fix this by teleporting with nothing in their hands

**Comment by TeaWald** [comment]
It`s a feature. Study quantum mechanics jk

**Comment by Lughbaloo** [comment]
I'm experiencing the same issue as SaladProphet

**Comment by stormytuna** [comment]
Closing as fixed in 45b1497217c3c7f53f5db293cddadce47fd6ce10 - Sorry for getting back to you late, this has been fixed for weeks and I just forgor :3
