### ISSUE TITLE
[suggestion] Implement this for inverse teleporter also? + Lethal things toolbelt compatibility

### ISSUE THREAD

**Issue by Darkmega18** [stormytuna/KindTeleporters#4]
Basically the name. it'd be nice if your mod would include both your tweak to allow bringing the item in hand and a tweak that lets you bring all items in hand through the inverse teleporter.

Also, if it's not already compatible, theres a mod called Lethal things, which adds a tool belt. it'd be a very interesting interaction if your teleporter tweaks would also work with the tool belt's additional slots.
Letting you effectively store some items on the toolbelt's 3 additional slots it creates while it's equipped to warp with them intact if it's the item in your hand when warping with your kind teleporter tweak.
_(I have the mod, I just haven't tested it personally as I haven't managed to have all the items at the same time solo yet... but I'd imagine it'd keep the toolbelt itself inhand but drop the items within it in the bonus slots)_

**Comment by stormytuna** [comment]
It works for the inverse teleporter already

As for the lethal things suggestion, I had a quick look at the [utility belts source code](https://github.com/EvaisaDev/LethalThings/blob/main/LethalThings/MonoBehaviours/PouchyBelt.cs) and I believe it should just work, I haven't actually tested it though so I could be wrong
